# Explore numpy Polynomial fits

In [1]:
import numpy as np


Hey y'all. I'm getting some weird behavior from numpy's Polynomial class.
When I fit a 1st degree polynomial to x = [0,1] and y = [2,4] numpy gives me this: y = 2.99999 + 1x.
which like... shouldn't it be y = 2 + 2x? 
does anybody here have experience w numpy polynomials?
or any ideas what's going on? some kind of crazy rounding issue?


### Default `window`

In [2]:
x = np.array([0,1])
y = np.array([2,4])
deg = 1
pfit = np.polynomial.Polynomial.fit(x, y, deg)
print(pfit)

2.9999999999999996 + 1.0000000000000002·x¹


In [3]:
pfit.__dict__

{'coef': array([3., 1.]),
 'domain': array([0., 1.]),
 'window': array([-1.,  1.])}

### Specify `window`

In [4]:
x = np.array([0,1])
y = np.array([2,4])
deg = 1
pfit2 = np.polynomial.Polynomial.fit(x, y, deg, window=[0,1])
print(pfit2)

1.9999999999999998 + 1.9999999999999998·x¹


In [5]:
pfit2.__dict__

{'coef': array([2., 2.]), 'domain': array([0., 1.]), 'window': array([0., 1.])}

### Alt. solution using least squares (linear algebra)

In [6]:
# Alt. solution using least squares (linear algebra)
x = np.array([0,1])
y = np.array([2,4])
X = np.vstack([x, np.ones(len(x))]).T
betas = np.linalg.lstsq(X, y, rcond=None)[0]
betas

array([2., 2.])

In [7]:
X

array([[0., 1.],
       [1., 1.]])

In [8]:
# Alt. solution using least squares (linear algebra)
x = np.array([0,1,3])
y = np.array([2,4,8])
X = np.vstack([x, np.ones(len(x))]).T
X

array([[0., 1.],
       [1., 1.],
       [3., 1.]])

In [9]:
betas = np.linalg.lstsq(X, y, rcond=None)[0]
betas

array([2., 2.])

### Confirm input space gets mapped to [-1,1] by default..

In [10]:
x = np.array([-1,1])
y = np.array([2,4])
deg = 1
pfit3 = np.polynomial.Polynomial.fit(x, y, deg)
print(pfit3)

2.9999999999999996 + 1.0000000000000002·x¹


In [11]:
pfit3.__dict__

{'coef': array([3., 1.]),
 'domain': array([-1.,  1.]),
 'window': array([-1.,  1.])}